/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Shop_FlowerShop */

#ifndef _Included_Shop_FlowerShop
#define _Included_Shop_FlowerShop
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     Shop_FlowerShop
	* Method:    printCheck
	* Signature: ([LFlowers/Flower;)[C
	*/
	JNIEXPORT jcharArray JNICALL Java_Shop_FlowerShop_printCheck
	(JNIEnv *, jobject, jobjectArray);

	/*
	* Class:     Shop_FlowerShop
	* Method:    calculate
	* Signature: ([LFlowers/Flower;)D
	*/
	JNIEXPORT jdouble JNICALL Java_Shop_FlowerShop_calculate
	(JNIEnv *, jobject, jobjectArray);

	/*
	* Class:     Shop_FlowerShop
	* Method:    summ
	* Signature: ([I)I
	*/
	JNIEXPORT jint JNICALL Java_Shop_FlowerShop_summ
	(JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif